Disable HSTS
giantswarm/kubernetes-nginx-ingress-controller pull request #23
Opened 2018-07-25 12:05 UTC by marians

Related to https://github.com/giantswarm/giantswarm/issues/3841

This change turns off strict HSTS headers which are normally set by NGINX ingress controller if HTTPS termination is performed in the IC.

https://github.com/kubernetes/ingress-nginx/issues/549#issuecomment-291894246 explains in more detail why that header can be harmful and should be activated consciously, as opposed to coming as an unexpected side effect.

Setting `hsts: "false"` in the configmap enables customers to use configuration snippet annotations like shown below in their ingress manifest in order to enable a custom HSTS header.

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Strict-Transport-Security: max-age=60; includeSubDomains;";
spec:
  ...
```

2018-07-25 12:44 UTC, indyfree approved these changes
Makes sense to me, when looking into the linked issue, but don't know all the implications. Maybe for awareness ping @giantswarm/sre

2018-07-25 13:36 UTC, r7vme requested changes
Thanks, but do we have real issue with this setting?

If not, then having HSTS enabled (which is really good security feature imo) is a way to go.

~Also see last comment from author that hsts can be disabled by setting `max-age=0`, which was workaround for his particular problem, keeping hsts enabled.~

~https://github.com/kubernetes/ingress-nginx/issues/549#issuecomment-294582915~

2018-07-25 13:54 UTC, r7vme approved these changes
Ok then. Please also update documentation

2018-07-27 13:18 UTC, rossf7 approved these changes
Reasons for disabling HSTS makes sense but not deep into that. Looks good from a deployment POV.

The release channel in cluster-operator will need updating to 0-2-stable and it will then go in the 1.1.0 release of azure-operator.

2018-07-27 14:34 UTC, merged